# Whether this GitHub repo is for a CC-led engineering project
engineering_project: true
# Name of the repository/project in English
english_name: Primary Site Includes
# All technologies used
technologies: Python
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
